version: "3.9"
services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: "lds_db"
            POSTGRES_USER: "lds_user"
            POSTGRES_PASSWORD: "ldsforever"
        ports:
            - "5432:5432"
   
    whodb:
        image: clidey/whodb
        environment:
            WHODB_POSTGRES_1: '{"host":"host.docker.internal","user":"lds_user","password":"ldsforever","database":"lds_db"}'
        ports:
            - "8080:8080"
    
    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        restart: unless-stopped
        environment:
            - GF_SECURITY_ADMIN_USER=max
            - GF_SECURITY_ADMIN_PASSWORD=1
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./config/grafana-provisioning:/etc/grafana/provisioning
        networks:
            - monitoring
    
    prometheus:
        image: prom/prometheus
        command: [ "--config.file=/etc/prometheus/prometheus.yml" ]
        ports:
            - 9090:9090
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus:/prometheus
        networks:
            - monitoring

    tempo:
        image: grafana/tempo:latest
        command: [ "-config.file=/etc/tempo.yaml" ]
        container_name: tempo
        ports:
            - '4317:4317' # OTLP gRPC endpoint
            - '3200:3200' # Tempo API endpoint
        volumes:
            - tempo-storage:/tmp/tempo/traces # Монтирование локальной директории
            - ./config/tempo.yaml:/etc/tempo.yaml
        networks:
            - monitoring

volumes:
    grafana-storage: {}
    tempo-storage: {}

networks:
    monitoring:
