version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "lds_db"
      POSTGRES_USER: "lds_user"
      POSTGRES_PASSWORD: "ldsforever"
    ports:
      - "5432:5432"
  whodb:
    image: clidey/whodb
    environment:
      WHODB_POSTGRES_1: '{"host":"host.docker.internal","user":"lds_user","password":"ldsforever","database":"lds_db"}'
    ports:
      - "8080:8080"